version: "3.9"

services:
  server:
    restart: always
    build: .
    image: flask-boilerplate
    container_name: flask-boilerplate-server
    command: python -m flask run --host=0.0.0.0
    volumes:
      - ./:/usr/src
    ports:
      - "5000:5000"
    env_file:
      - .env
